#!/usr/bin/python

import sys
from config import *

default_args = [
    ('--username', 'admin'),
    ('--password', 'contrail123'),
    ('--region', 'RegionOne'),
    ('--tenant', 'admin'),
    ('--api-server', '127.0.0.1')]

if __name__ == '__main__':
    for arg in default_args:
        if not arg[0] in sys.argv:
            sys.argv.insert(1, arg[0])
            sys.argv.insert(2, arg[1])
    shell = ConfigShell()
    parser = shell.parser_init()
    args = parser.parse_args()
    shell.clients_init(args)
    shell.execute(args)

