#!/usr/bin/python

import sys
import time
import argparse
import paramiko
from config_obj import *
from ncclient import manager as netconf
from ncclient.xml_ import *

class VpnService():
    def __init__(self, client):
        self.mgmt_addr = None
        self.client = client
        self.name = 'vsrx-vpn-' + client.tenant.name
        self.svc = ConfigServiceInstance(client = client)

    def mgmt_addr_get(self):
        vm = self.client.nova.servers.find(name = self.name + '_1')
        mgmt_addr = vm.addresses['management'][0]['addr']
        return mgmt_addr

    def obj_check(self, name):
        for item in self.svc.obj_list():
            if (item['fq_name'][2] == name):
                return True

    def show(self, name = None):
        if self.obj_check(self.name):
            print 'Service exists.'
        else:
            print 'No service.'

    def add(self, name):
        if self.obj_check(self.name):
            print 'Service exists.'
            return
        print 'Launch service instance.'
        vn = ConfigNetwork(client = self.client)
        vn_name = 'vpn-' + self.client.tenant.name
        vn.add(name = vn_name, ipam = 'ipam-default', subnet = '100.64.10.0/24')
        self.svc.add(name = self.name, template = 'vsrx-vpn',
                mgmt_net = 'admin:management',
                left_net = vn_name, right_net = 'admin:public')
        count = 0
        while (count < 10):
            print 'Waiting for VM to be created...%d' %(count)
            try:
                vm = self.client.nova.servers.find(name = self.name + '_1')
                print 'VM is created.'
                break
            except:
                count += 1
                time.sleep(3)

        count = 0
        while (count < 10):
            print 'VM is in the state of %s...%d' %(vm.status, count)
            vm = self.client.nova.servers.find(name = self.name + '_1')
            if vm.status == 'ACTIVE':
                print 'VM %s is %s' %(vm.name, vm.status)
                break
            count += 1
            time.sleep(2)
        self.mgmt_addr = vm.addresses['management'][0]['addr']

        print 'Post-launch configuration.'
        vm_if = ConfigVmInterface(client = self.client)
        vm_if.delete(name = vn_name, sg = 'default', vm_id = vm.id)
        vm_if.delete(name = 'management', sg = 'default', vm_id = vm.id)
        vm_if.delete(name = 'public', sg = 'default', vm_id = vm.id)

        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        count = 0
        while True:
            print 'Waiting for service booting up...%d' %(count)
            try:
                ssh.connect(self.mgmt_addr, username = 'root',
                        password = 'passWD', timeout = 5)
                print 'Service is up.'
                break
            except:
                count += 1

        print 'Prepare for provisioning service...'
        cmd = 'cli -c "configure;' + \
                'set system services netconf ssh;' + \
                'set security zones security-zone trust interfaces ' + \
                    'ge-0/0/0.0 host-inbound-traffic system-services all;' + \
                'commit"'
        ssh.exec_command(cmd)
        time.sleep(10)
        ssh.close()
        print 'Service is up and running.'

    def delete(self, name):
        if not self.obj_check(self.name):
            print 'No service to be deleted.'
            return
        self.svc.delete(self.name)
        count = 0
        while (count < 15):
            print 'Waiting for VM instance to be deleted...%d' %(count)
            try:
                vm = self.client.nova.servers.find(name = self.name + '_1')
                count += 1
                time.sleep(2)
                continue
            except:
                print 'Service instance is deleted.'
                break
        print 'Waiting for clean up...'
        time.sleep(10)
        vn = ConfigNetwork(client = self.client)
        vn_name = 'vpn-' + self.client.tenant.name
        vn.delete(name = vn_name)
        print 'Service is deleted.'


class VpnNetconf():
    def __init__(self):
        self.client = None

    def session_open(self, svc_client):
        service = VpnService(svc_client)
        print 'Looking for service...'
        if not service.obj_check(service.name):
            print 'No service available.'
            return
        mgmt_addr = service.mgmt_addr_get()
        self.client = netconf.connect(host = mgmt_addr, port = 830,
                username = 'root', password = 'passWD',
                hostkey_verify = False, device_params={'name':'junos'})
        return self.client

    def session_close(self):
        self.client.close_session()



class VpnIkePolicy():
    def __init__(self, client):
        self.client = client

    def show(self, name = None):
        nc = VpnNetconf()
        nc_client = nc.session_open(self.client)
        if not nc_client:
            return

        root_filter = new_ele('filter')
        config_filter = sub_ele(root_filter, 'configuration')
        system_filter = sub_ele(config_filter, 'security')
        sub_ele(system_filter, 'ike')
        result = nc_client.get_config('running', filter = root_filter)

        ike = result.xpath('data/configuration/security/ike')[0]
        for policy in ike.xpath('policy'):
            print '\n', policy.xpath('name')[0].text
            if policy.xpath('mode'):
                print '  phase 1 mode:', policy.xpath('mode')[0].text
            proposal_name = policy.xpath('proposals')[0].text
            for proposal in ike.xpath('proposal'):
                if (proposal.xpath('name')[0].text == proposal_name):
                    if proposal.xpath('authentication-algorithm'):
                        print '  authentication-algorithm:', \
                            proposal.xpath('authentication-algorithm')[0].text
                    if proposal.xpath('encryption-algorithm'):
                        print '  encryption-algorithm:', \
                            proposal.xpath('encryption-algorithm')[0].text
        nc.session_close()

    def add(self, name, auth_algo = None, encryp_algo = None, mode = None):
        nc = VpnNetconf()
        nc_client = nc.session_open(self.client)
        if not nc_client:
            return

        print 'Adding...'
        list = []
        list.append('set security ike proposal %s authentication-method pre-shared-keys' %(name))
        list.append('set security ike proposal %s dh-group group2' %(name))
        list.append('set security ike policy %s proposals %s' %(name, name))
        list.append('set security ike policy %s pre-shared-key ascii-text "$9$W-FxVwGDiPTzZU9pBRle4aZUjqf5F6CuTQcl"' %(name))
        if auth_algo:
            list.append('set security ike proposal %s authentication-algorithm %s' %(name, auth_algo))
        if encryp_algo:
            list.append('set security ike proposal %s encryption-algorithm %s' %(name, encryp_algo))
        if mode:
            list.append('set security ike policy %s mode %s' %(name, mode))

        nc_client.load_configuration(action = 'set', config = list)
        nc_client.commit()
        nc.session_close()
        time.sleep(3)
        print 'Done.'

    def delete(self, name):
        nc = VpnNetconf()
        nc_client = nc.session_open(self.client)
        if not nc_client:
            return

        print 'Deleting...'
        list = []
        list.append('delete security ike proposal %s' %(name))
        list.append('delete security ike policy %s' %(name))

        nc_client.load_configuration(action = 'set', config = list)
        nc_client.commit()
        nc.session_close()
        time.sleep(3)
        print 'Done.'


class VpnIpsecPolicy():
    def __init__(self, client):
        self.client = client

    def show(self, name = None):
        nc = VpnNetconf()
        nc_client = nc.session_open(self.client)
        if not nc_client:
            return

        root_filter = new_ele('filter')
        config_filter = sub_ele(root_filter, 'configuration')
        system_filter = sub_ele(config_filter, 'security')
        sub_ele(system_filter, 'ipsec')
        result = nc_client.get_config('running', filter = root_filter)

        ipsec = result.xpath('data/configuration/security/ipsec')[0]
        for policy in ipsec.xpath('policy'):
            print '\n', policy.xpath('name')[0].text
            proposal_name = policy.xpath('proposals')[0].text
            for proposal in ipsec.xpath('proposal'):
                if (proposal.xpath('name')[0].text == proposal_name):
                    if proposal.xpath('authentication-algorithm'):
                        print '  authentication-algorithm:', \
                            proposal.xpath('authentication-algorithm')[0].text
                    if proposal.xpath('encryption-algorithm'):
                        print '  encryption-algorithm:', \
                            proposal.xpath('encryption-algorithm')[0].text
        nc.session_close()

    def add(self, name, auth_algo = None, encryp_algo = None):
        nc = VpnNetconf()
        nc_client = nc.session_open(self.client)
        if not nc_client:
            return

        print 'Adding...'
        list = []
        list.append('set security ipsec proposal %s protocol esp' %(name))
        list.append('set security ipsec policy %s proposals %s' %(name, name))
        list.append('set security ipsec policy %s perfect-forward-secrecy keys group2' %(name))
        if auth_algo:
            list.append('set security ipsec proposal %s authentication-algorithm %s' %(name, auth_algo))
        if encryp_algo:
            list.append('set security ipsec proposal %s encryption-algorithm %s' %(name, encryp_algo))

        nc_client.load_configuration(action = 'set', config = list)
        nc_client.commit()
        nc.session_close()
        time.sleep(3)
        print 'Done.'

    def delete(self, name):
        nc = VpnNetconf()
        nc_client = nc.session_open(self.client)
        if not nc_client:
            return

        print 'Deleting...'
        list = []
        list.append('delete security ipsec proposal %s' %(name))
        list.append('delete security ipsec policy %s' %(name))

        nc_client.load_configuration(action = 'set', config = list)
        nc_client.commit()
        nc.session_close()
        time.sleep(3)
        print 'Done.'


class VpnConnection():
    def __init__(self):
        pass

    def show(self, args):
        print args

    def add(self, args):
        print args

    def delete(self, args):
        print args


class VpnShell():

    def __init__(self):
        self.parser_init()

    def do_help(self, args):
        if args.obj_parser:
                args.obj_parser.print_help()
        else:
            self.parser.print_help()

    def parser_init(self):
        parser = argparse.ArgumentParser()
        parser.add_argument('--api-server', help = 'API server address')
        parser.add_argument('--username', help = 'User name')
        parser.add_argument('--password', help = 'Password')
        parser.add_argument('--tenant', help = 'Tenant name')
        parser.add_argument('--region', help = 'Region name')
        cmd_list = ['add', 'show', 'delete', 'help']
        parser.add_argument('cmd', choices = cmd_list)

        subparsers = parser.add_subparsers()
        self.sub_cmd_dict = {}

        sub_parser = subparsers.add_parser('service')
        sub_parser.set_defaults(obj_class = VpnService,
                obj_parser = sub_parser)
        sub_parser.add_argument('name', nargs = '?', default = None)

        sub_parser = subparsers.add_parser('ike-policy')
        sub_parser.set_defaults(obj_class = VpnIkePolicy,
                obj_parser = sub_parser)
        sub_parser.add_argument('name', nargs = '?', default = None)
        sub_parser.add_argument('--auth-algorithm',
                choices = ['sha1', 'sha-256', 'sha-384', 'md5'],
                metavar = '[ sha1 | sha-256 | sha-384 | md5 ]',
                help = 'Authentication algorithm')
        sub_parser.add_argument('--encryption-algorithm',
                choices = ['3des-cbc', 'aes-128-cbc', 'aes-192-cbc',
                          'aes-256-cbc', 'des-cbc'],
                metavar = '[ 3des-cbc | aes-128-cbc | aes-192-cbc | ' +
                          'aes-256-cbc | des-cbc ]',
                help = 'Encryption algorithm')
        sub_parser.add_argument('--phase1-mode',
                choices = ['aggressive', 'main'],
                metavar = '[ aggressive | main ]',
                help = 'IKE phase 1 negotiation mode')

        sub_parser = subparsers.add_parser('ipsec-policy')
        sub_parser.set_defaults(obj_class = VpnIpsecPolicy,
                obj_parser = sub_parser)
        sub_parser.add_argument('name', nargs = '?', default = None)
        sub_parser.add_argument('--auth-algorithm',
                choices = ['hmac-md5-96', 'hmac-sha-256-128', 'hmac-sha1-96'],
                metavar = '[ hmac-md5-96 | hmac-sha-256-128 | hmac-sha1-96 ]',
                help = 'Authentication algorithm')
        sub_parser.add_argument('--encryption-algorithm',
                choices = ['3des-cbc', 'aes-128-cbc', 'aes-192-cbc',
                          'aes-256-cbc', 'des-cbc'],
                metavar = '[ 3des-cbc | aes-128-cbc | aes-192-cbc | ' +
                          'aes-256-cbc | des-cbc',
                help = 'Encryption algorithm')

        sub_parser = subparsers.add_parser('connection')
        sub_parser.set_defaults(obj_class = VpnConnection,
                obj_parser = sub_parser)
        sub_parser.add_argument('name', nargs = '?', default = None)
        sub_parser.add_argument('--src-subnet',
                metavar = '<prefix/prefix-length>',
                help = 'Source subnet address')
        sub_parser.add_argument('--dst-subnet',
                metavar = '<prefix/prefix-length>',
                help = 'Destination subnet address')
        sub_parser.add_argument('--ike-policy',
                metavar = '<IKE policy>',
                help = 'IKE policy')
        sub_parser.add_argument('--ipsec-policy',
                metavar = '<IPsec policy>',
                help = 'IPsec policy')
        sub_parser.add_argument('--peer-address',
                metavar = '<address>',
                help = 'IP address of connection peer')

        self.parser = parser

    def parse(self, argv = None):
        args = self.parser.parse_args(args = argv)
        return args

    def run(self, args):
        client = ConfigClient(args.username, args.password, args.tenant,
                args.api_server, args.region)
        obj = args.obj_class(client)
        if args.cmd == 'show':
            obj.show(args.name)
        elif args.cmd == 'help':
            self.do_help(args)
        elif args.cmd == 'add':
            if (args.obj_class == VpnService):
                obj.add(args.name)
            elif (args.obj_class == VpnIkePolicy):
                obj.add(args.name, args.auth_algorithm,
                        args.encryption_algorithm, args.phase1_mode)
            elif (args.obj_class == VpnIpsecPolicy):
                obj.add(args.name, args.auth_algorithm,
                        args.encryption_algorithm)
            elif (args.obj_class == VpnConnection):
                obj.add(args.name, args.src_subnet, args.dst_subnet,
                        args.ike_policy, args.ipsec_policy, args.peer_address)
        elif args.cmd == 'delete':
            if (args.obj_class == VpnService):
                obj.delete(None)
            elif (args.obj_class == VpnIkePolicy):
                obj.delete(args.name)
        else:
            print 'Unknown action %s' %(args.cmd)
            return

    def main(self):
        args = self.parse()
        self.run(args)


default_client_args = [
    ('--username', 'admin'),
    ('--password', 'contrail123'),
    ('--region', 'RegionOne'),
    ('--tenant', 'admin'),
    ('--api-server', '127.0.0.1')]

if __name__ == '__main__':
    for arg in default_client_args:
        if not arg[0] in sys.argv:
            sys.argv.insert(1, arg[0])
            sys.argv.insert(2, arg[1])
    VpnShell().main()

